<template>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        Generated by <a href="http://opensource.org/licenses/mit-license.php">Helm Charts Docs</a> v0.1.0.
      </p>
    </div>
  </footer>
</template>
<script lang="ts">
import {defineComponent} from "@vue/composition-api";

export default defineComponent({
  name: "Footer"
});
</script>
