<template>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        Generated by <a href="https://github.com/marketplace/actions/helm-chart-docs-github-pages" target="_blank">Helm
        Charts Docs</a> v0.1.0.
      </p>
    </div>
  </footer>
</template>
<script lang="ts">
import {defineComponent} from "@vue/composition-api";

export default defineComponent({
  name: "Footer"
});
</script>
